---
title: "FigS1_SamplingMap.Rmd"
author: "Emerson"
date: "3/25/2022"
output: html_document
---


## Load libraries


```{r}
library(rnaturalearth)
library(rnaturalearthhires)
library(gsheet)
library(tidyverse)
library(janitor)
```

## Load the data

```{r}


tab1 <- readxl::read_excel("SamplingLocations.xlsx")
```

## Prepare the data

```{r}

# Select columns
tab2 <- tab1 %>% 
  dplyr::select(host_genus, region2, lat, lon, lineage)

# Prepare the wide format
tab_genus <- tab2 %>% 
    dplyr::count(host_genus, region2) %>% 
  pivot_wider(names_from = "host_genus",
              values_from = "n") |> 
  arrange(region2)

# Coordinate for each location
coord_region2 <- tab2 %>% 
  select(region2, lat, lon) %>% 
  group_by(region2) %>% 
  slice(1)

# Join the datasets
dat_newmap <- left_join(tab_genus, coord_region2)

# Change NA for 0
dat_newmap[is.na(dat_newmap)] = 0

# Sum the number of isolates per region
dat_newmap$n <- rowSums(dat_newmap[,2:15])

# Create the distance class
dat_newmap$distance <- c("Away",  #1
                         "Away",   #2
                         "Away",   #3
                         "Away",   #4
                         "Away",   #5
                         "Away", #6
                         "Nearby", #7
                         "Nearby", #8
                         "Nearby", #9
                         "Away",  #10
                         "Away",  #11
                         "Away",  #12
                         "Away",  #13
                         "Nearby")#14

dat_newmap$source <- c("P",  #1
                         "M",   #2
                         "M",   #3
                         "M",   #4
                         "A",   #5
                         "A", #6
                         "A", #7
                         "C", #8
                         "C", #9
                         "M",  #10
                         "M",  #11
                         "M",  #12
                         "A", # 14
                       "K")  #14


```


```{r}
library(RColorBrewer)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
myColors = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
```


```{r}
world <- ne_countries(scale = "large", returnclass = "sf")
class(world)

library(scatterpie)
library(ggspatial)

ggplot() +
  geom_sf(data = world, fill = "grey96", color = "grey50", alpha = 0.7, size = 0.3)+
 coord_sf(xlim = c(-62, -39.6), ylim = c(-38, -15), expand = FALSE)+
  theme_minimal()+ 
  theme(legend.text = element_text(size = 9, face = "italic"))+
  annotation_north_arrow(which_north = "grid", location = "tl", width = unit(1, "cm"))+
  annotation_scale(location = "br") +
  geom_scatterpie(aes(x=lon, 
                      y=lat, 
                      group=region2,
                      r =0.6, 
                  linetype = distance), size =0.5,
                  data=dat_newmap, 
                  cols=c("Avena","Cenchrus","Cynodon",  "Digitaria","Echinochloa","Eleusine","Elionorus","Lolium","Luziola","Melinis","Oryza","Setaria","Urochloa", "Bromus"))+
scale_fill_manual(values = myColors)+
  scale_linetype_manual(values = c("solid", "dashed"))+
 #   geom_text(data = dat_newmap, aes(lon, lat, label = n),
   #        vjust = 2.4, hjust = 1, size = 2)+
  #   geom_text(data = dat_newmap, aes(lon, lat, label = source),
   
  #       vjust = 2.4, hjust = 1.7, size = 2)+
  
  annotate(geom = "text", size =3,  x = -57, y = -32, label = "Uruguay")+
   annotate(geom = "text", size = 3, x = -58, y = -24, label = "Paraguay")+
     annotate(geom = "text", size = 3, x = -49, y = -22, label = "Brazil")+
  labs(fill = "Host genus", x = "Longitude", y = "Latitude")+
scale_linetype(guide = 'none')

ggsave("FigS1_SamplingMap.png", dpi = 600, bg = "white")
#ggsave("FigS1_SamplingMap.pdf", dpi = 600, bg = "white")
```









